name: todolist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  equatable: ^2.0.3
  flutter_easyloading: ^3.0.3
  dotted_border: ^2.0.0+2
  step_progress_indicator: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_app_name: ^0.1.1
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.9.2
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  color_dark: "#000000"
  image_dark: assets/splash.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash.png"
flutter_app_name:
  name: "Tasklly"

flutter:


  uses-material-design: true

  assets:
    - assets/


